# Generated by Django 5.0.6 on 2024-06-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empleado_delete_item_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
