# Generated by Django 5.0.6 on 2024-06-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_empleado_contrasena_empleado_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depa', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_depa', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
